### ISSUE TITLE
Encrypt secrets using only service accounts

### ISSUE THREAD

**Issue by mcanaves** [Soluto/kamus#584]
**General remarks**
At my company we have developed a new functionality to allow developers to have on-demand QA environments. Each environment is isolated using namespaces, so each environment lives in a unique namespace. These environments are based on templates. To be the perfect solution will be nice if secrets could be encrypted in the templates. Solution for the service accounts is easy, every single service in every environment has the same service account but for namespace names, it's not trivial as each is unique and created on the fly.

**Describe the solution you'd like**
Allow encrypt secrets only with a service account.

**Comment by shaikatz** [comment]
Hi @mcanaves,
That sounds like a pretty specific use case for your environment, so maybe instead of implementing such a feature, which encourages bad practice, and might be accidentally used by users in a production cluster, we can think about a solution in your CI/CD pipeline?

What if as part of your namespace creation flow, you will also use kamus-cli to encrypt those secrets for the newly created namespace?
Can it work for you?

**Comment by shaikatz** [comment]
Close due to being stale.
